---
Parameters:
  ProjectName:
    Type: String
    Default: cloudfront-kv-redirect

  Domain:
    Type: String

  CloudFrontKeyValueStore:
    Type: String

  CertificateArn:
    Type: String

Resources:
  CloudfrontFunction:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: true
      FunctionCode: !Join
        - ''
        - - 'import cf from "cloudfront";'
          - 'const kvsId = "'
          - !Ref CloudFrontKeyValueStore
          - '";'
          - 'const kvsHandle = cf.kvs(kvsId); async function handler(event) { const k = event.request.uri.split("/")[1]; try { let v = await kvsHandle.get(k); return { statusCode: 302, statusDescription: "Redirect found", headers: { "location": { "value": v } } } } catch (e) { console.log(`Kvs key lookup failed for ${k}: ${e}`); return { statusCode: 404, statusDescription: "Redirect not found", body: "Not found" } } }'
      FunctionConfig:
        Comment: Redirect to a new url
        Runtime: cloudfront-js-2.0
      Name: !Ref ProjectName

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        HttpVersion: http2and3
        Origins:
          - DomainName: !Ref Domain
            Id: PrimaryOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: PrimaryOrigin
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !Ref CloudfrontFunction
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

Outputs:
  CloudfrontDistributionUrl:
    Description: Cloudfront
    Value: !Sub
      - 'https://${Domain}'
      - Domain: !GetAtt CloudfrontDistribution.DomainName
